### PR TITLE
fixed yolo batchsize and 608 bug

### PR DESCRIPTION
**Pull request by ZHEQIUSHUI**

### CODE REVIEW

**Comment by zerollzeng** [comment]
Thanks for your contribution! did you test the new code in both 416 and 608 net_size input? if so I will merge your commit to master directly.

**Comment by zerollzeng** [comment]
And since you modify Yolov3.h and Yolov3.cpp, you need to modify yolov3test.cpp, too. or replace it with your test script that can show how to use the new api :dancers:

**Comment by ZHEQIUSHUI** [comment]
yes,i have test 416 and 608,i will upload a new test code file after 5.1,it will demonstrate how to use 608 and forward two images in one batch

**Comment by zerollzeng** [comment]
Thanks for you contribution and happy labor day! may the 996, 251, 18000 far from you :D

**Pull request merged**
